[2024-06-21T12:39:59.627+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-21T12:39:59.640+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branchtest.branch_task manual__2024-06-21T12:39:57.742416+00:00 [queued]>
[2024-06-21T12:39:59.645+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branchtest.branch_task manual__2024-06-21T12:39:57.742416+00:00 [queued]>
[2024-06-21T12:39:59.645+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-21T12:39:59.653+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_task> on 2024-06-21 12:39:57.742416+00:00
[2024-06-21T12:39:59.657+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1166) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-21T12:39:59.658+0000] {standard_task_runner.py:63} INFO - Started process 1167 to run task
[2024-06-21T12:39:59.658+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'branchtest', 'branch_task', 'manual__2024-06-21T12:39:57.742416+00:00', '--job-id', '407', '--raw', '--subdir', 'DAGS_FOLDER/brachs.py', '--cfg-path', '/tmp/tmpt0uftklg']
[2024-06-21T12:39:59.659+0000] {standard_task_runner.py:91} INFO - Job 407: Subtask branch_task
[2024-06-21T12:39:59.683+0000] {task_command.py:426} INFO - Running <TaskInstance: branchtest.branch_task manual__2024-06-21T12:39:57.742416+00:00 [running]> on host 55c563b9c0dc
[2024-06-21T12:39:59.731+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branchtest' AIRFLOW_CTX_TASK_ID='branch_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-21T12:39:57.742416+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-21T12:39:57.742416+00:00'
[2024-06-21T12:39:59.732+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-21T12:39:59.739+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-21T12:39:59.745+0000] {python.py:237} INFO - Done. Returned value was: odd_task
[2024-06-21T12:39:59.746+0000] {branch.py:36} INFO - Branch into odd_task
[2024-06-21T12:39:59.746+0000] {skipmixin.py:178} INFO - Following branch odd_task
[2024-06-21T12:39:59.754+0000] {skipmixin.py:246} INFO - Skipping tasks [('even_task', -1)]
[2024-06-21T12:39:59.767+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-21T12:39:59.777+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=branchtest, task_id=branch_task, run_id=manual__2024-06-21T12:39:57.742416+00:00, execution_date=20240621T123957, start_date=20240621T123959, end_date=20240621T123959
[2024-06-21T12:39:59.791+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-21T12:39:59.812+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-21T12:39:59.814+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
