[2024-06-20T13:52:36.856+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: emailtestallsuccess3.task1 manual__2024-06-20T13:52:23.473085+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
